version: "3"

networks:
  local:
    driver: bridge

services:
  app:
    image: lglot/sparql_endpoint_availability:v0.1
    container_name: app
    networks:
      - local
    #build:
    #  context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sparql_endpoint_availability?serverTimezone=Europe/Rome
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
      - APP_ADMIN_PASSWORD=${APPLICATION_ADMIN_PASSWORD}

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env
    networks:
      - local
    environment:
      MYSQL_DATABASE: sparql_endpoint_availability
    volumes:
      - db_volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_volume:
    external: false
