name: Build Test and Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v3

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please don't remove it

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'sparql_endpoint_availability'
          mysql root password: ${{ secrets.MYSQL_PASSWORD }} 

      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Test with Maven
        run: mvn -B test -fae
        env:
           SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
           SPRING_PROFILES_ACTIVE: 'mysql'

      # test result maven surefire report
      - name: Surefire Report
        if: ${{always()}}
        uses: ScaCap/action-surefire-report@v1


      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/surefire-reports/*.xml"

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .
  deploy:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image e push to DockerHub 
        run: |
          mvn -B package
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
          docker image build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/sparql_endpoint_availability:v0.1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/sparql_endpoint_availability:v0.1
        env:
           SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}


      
      
      


      
      
      
